sonar.projectKey=root_software-factory_c0a1453c-752b-438e-b86b-311ac2555bb4
sonar.qualitygate.wait=true
sonar.javascript.lcov.reportPaths=mcp/gitlab/coverage/lcov.info,apps/chat/coverage/lcov.info
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
